name: hunyuan_gpu
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - pip:
    - -r package_versions.txt
